// ============================================================
// Auto-Generate Runs: Power Source → Charger Zone Routing
// ============================================================

import { lineString } from '@turf/helpers';
import turfLength from '@turf/length';
import type { LineString, Point } from 'geojson';
import type { RunSegment, EquipmentPlacement } from './types';
import { CONDUIT_ROUTING_FACTOR } from './constants';

interface SurfaceAnalysis {
  readonly primarySurface: 'asphalt' | 'concrete' | 'gravel' | 'other' | null;
  readonly surfaceTransitions: readonly string[];
}

interface GeneratedRunsResult {
  readonly runs: readonly RunSegment[];
  readonly equipment: readonly EquipmentPlacement[];
}

function nextAutoId(prefix: string): string {
  return `${prefix}-auto-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Measure straight-line distance between two [lng, lat] coordinates in feet.
 */
function measureStraightLineFt(a: [number, number], b: [number, number]): number {
  const feature = lineString([a, b]);
  const miles = turfLength(feature, { units: 'miles' });
  return Math.round(miles * 5280 * 100) / 100;
}

/**
 * Determine civil work type based on AI-detected surface.
 * - Asphalt → trench (softer, saw-cut + trench)
 * - Concrete → bore (hard surface, directional bore underneath)
 * - Gravel → trench (loose material)
 * - Mixed/transitions → defaults to bore (conservative)
 */
function determineCivilType(surface: SurfaceAnalysis): 'trench' | 'bore' {
  if (surface.primarySurface === 'concrete') return 'bore';
  if (surface.primarySurface === 'asphalt' || surface.primarySurface === 'gravel') return 'trench';
  // Mixed or unknown — bore is the conservative default
  if (surface.surfaceTransitions.length > 0) return 'bore';
  return 'trench';
}

/**
 * Generate run segments and equipment placements from power source + charger zones.
 *
 * For each charger location:
 * 1. Calculate straight-line distance to power source
 * 2. Apply CONDUIT_ROUTING_FACTOR (1.3x) for conduit distance
 * 3. Determine civil work type from AI surface analysis
 * 4. Create LineString geometry from power source → charger
 * 5. Generate conduit run (full routed distance) + civil run (straight-line distance)
 */
export function autoGenerateRuns(
  powerSource: [number, number],
  chargerZones: readonly [number, number][],
  surface: SurfaceAnalysis,
  chargingLevel: 'l2' | 'l3_dcfc',
): GeneratedRunsResult {
  if (chargerZones.length === 0) {
    return { runs: [], equipment: [] };
  }

  const runs: RunSegment[] = [];
  const equipment: EquipmentPlacement[] = [];
  const civilType = determineCivilType(surface);
  const now = new Date().toISOString();

  // Power source equipment marker
  equipment.push({
    id: nextAutoId('eq'),
    equipmentType: 'utility_meter',
    geometry: { type: 'Point', coordinates: powerSource },
    label: 'Power Source',
    properties: { autoGenerated: true },
  });

  for (let i = 0; i < chargerZones.length; i++) {
    const chargerCoord = chargerZones[i];
    const straightLineFt = measureStraightLineFt(powerSource, chargerCoord);
    const conduitDistanceFt = Math.round(straightLineFt * CONDUIT_ROUTING_FACTOR * 100) / 100;

    // Separate geometry objects to avoid aliasing between runs
    const conduitGeometry: LineString = {
      type: 'LineString',
      coordinates: [powerSource, chargerCoord],
    };
    const civilGeometry: LineString = {
      type: 'LineString',
      coordinates: [powerSource, chargerCoord],
    };

    // Conduit run (full routed distance)
    runs.push({
      id: nextAutoId('run'),
      runType: 'conduit',
      geometry: conduitGeometry,
      lengthFt: conduitDistanceFt,
      label: `Conduit to Charger ${i + 1}: ${Math.round(conduitDistanceFt)}ft`,
      createdAt: now,
    });

    // Civil run (straight-line distance for trenching/boring)
    runs.push({
      id: nextAutoId('run'),
      runType: civilType,
      geometry: civilGeometry,
      lengthFt: straightLineFt,
      label: `${civilType === 'bore' ? 'Bore' : 'Trench'} to Charger ${i + 1}: ${Math.round(straightLineFt)}ft`,
      createdAt: now,
    });

    // Charger equipment marker
    const equipmentType = chargingLevel === 'l3_dcfc' ? 'charger_l3' : 'charger_l2';
    equipment.push({
      id: nextAutoId('eq'),
      equipmentType,
      geometry: { type: 'Point', coordinates: chargerCoord },
      label: `${chargingLevel === 'l3_dcfc' ? 'L3 DCFC' : 'L2 Charger'} ${i + 1}`,
      properties: { autoGenerated: true },
    });
  }

  return { runs, equipment };
}
