-- M4 Swarm A Task #9: pricing_catalog.
-- Seed catalog used by the estimate engine. product_id is stable (derived from category + description).
-- Seed rows are generated from src/lib/estimate/data/pricingCatalog.json (scripts/gen-pricing-catalog-sql.mjs).
-- Forward-only. Re-running this migration is safe: ON CONFLICT DO NOTHING preserves operator edits.

create table if not exists public.pricing_catalog (
  product_id   text primary key,
  description  text not null,
  unit         text,
  unit_cost    numeric(12, 4) not null default 0,
  category     text not null,
  markup       numeric(6, 4) not null default 1.0,
  active       boolean not null default true,
  metadata     jsonb not null default '{}'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists pricing_catalog_category_idx on public.pricing_catalog (category);
create index if not exists pricing_catalog_active_idx on public.pricing_catalog (active);

drop trigger if exists trg_pricing_catalog_set_updated_at on public.pricing_catalog;
create trigger trg_pricing_catalog_set_updated_at
before update on public.pricing_catalog
for each row execute function public.set_updated_at();

-- Seed rows (158 products, sorted by product_id for determinism).
insert into public.pricing_catalog
  (product_id, description, unit, unit_cost, category, markup, active, metadata)
values
  ('charger-chargepoint-cp6021b-50a-l5-5', 'ChargePoint CP6021B-50A-L5.5', 'CP6021B-50A', 8214.26, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('charger-chargepoint-cp6021b-80a-l5-5-dual-port-pedestal-mounted-18-cable', 'ChargePoint CP6021B-80A-L5.5 - Dual Port, Pedestal Mounted, 18'' Cable', 'EA', 11396.81, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-chargepoint-cp6621b-80a-l5-5-dual-port-pedestal-mounted-23-cable', 'ChargePoint CP6621B-80A-L5.5 - Dual Port, Pedestal Mounted, 23'' Cable', 'EA', 10851.74, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-chargepoint-cpf50-dual-pedestal-with-cmk', 'ChargePoint CPF50 – Dual Pedestal with CMK', null, 3130, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('charger-chargepoint-cpf50-dual-port-pedestal-mounted', 'ChargePoint CPF50 - Dual Port, Pedestal Mounted', 'EA', 5460.89, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-chargepoint-cpf50-l18-pedmnt-cmk6-dual-gw-usa', 'ChargePoint CPF50 - L18-PEDMNT-CMK6-DUAL-GW-USA', 'CPF50 - Dual', 3165, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('charger-chargepoint-ct4013-single-port-wall-mounted-18-cable', 'ChargePoint CT4013 - Single Port, Wall Mounted, 18'' Cable', 'EA', 5845.5, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-chargepoint-ct4021-dual-port-pedestal-mounted-18-cable', 'ChargePoint CT4021 - Dual Port, Pedestal Mounted, 18'' Cable', 'EA', 8251.2, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-chargepoint-ct4021-gw1-dual-output-bollard-unit-chgpnt-ct4001-ccm-concrete-mountin', 'ChargePoint CT4021 – GW1 DUAL OUTPUT BOLLARD UNIT + CHGPNT CT4001-CCM (Concrete Mounting Kit)', 'CT4021 - Dual', 7934.09, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('charger-chargepoint-ct4025-dual-port-pedestal-mounted-23-cable', 'ChargePoint CT4025 - Dual Port, Pedestal Mounted, 23'' Cable', 'EA', 8919.8, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('charger-tesla-universal-wall-connector-gen-3-model-1734412-02', 'Tesla Universal Wall Connector (Gen 3) – Model 1734412‑02', 'EA', 710, 'CHARGER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-asphalt-removal', 'Asphalt Removal', 'SF', 8.5, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-asphalt-restoration', 'Asphalt Restoration', 'SF', 33, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-boring-by-hand-under-hard-surface', 'Boring by hand (Under hard surface)', 'per foot', 40, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('civil-concrete-curb-gutter-6-in-x-24-in', 'Concrete Curb & Gutter, 6 in X 24 in', 'LF', 80, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-concrete-cutting-trenching', 'Concrete Cutting & Trenching', null, 45, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('civil-concrete-header-curb-6-in', 'Concrete Header Curb, 6 in', 'LF', 50, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-concrete-pads-for-pedestals', 'Concrete Pads for Pedestals', 'EA', 600, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-concrete-removal', 'Concrete Removal', 'CY', 725, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-concrete-restoration', 'Concrete Restoration', 'CY', 600, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-core-drilling-1-6-concrete-cmu', 'Core Drilling 1"-6" concrete/CMU', 'EA', 550, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-core-drilling-6-concrete-cmu', 'Core Drilling >6" concrete/CMU', 'EA', 800, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-coring-slab-scanning-for-conduit-routing', 'Coring & Slab Scanning For Conduit Routing', null, 312, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('civil-curb-removal', 'Curb Removal', 'LF', 24, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-encasement-of-conduits', 'Encasement of Conduits', 'CY', 450, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-install-3000-psi-concrete-pads', 'Install 3000 Psi Concrete Pads', 'per pedestal location & will involve a second visit (minimum order is 2)', 650, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('civil-scan-x-ray-wall-floor', 'Scan/X-ray-Wall/Floor', 'EA', 600, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('civil-trenching-assuming-soft-normal-soil-conditions', 'Trenching (assuming soft/normal soil conditions)', 'per foot', 30, 'CIVIL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('des-eng-as-built-drawings', 'As-Built Drawings', 'For when a permit is approved but then things change & you deviate from the plan', 500, 'DES/ENG', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('des-eng-engineered-and-stamped-plan-set', 'Engineered And Stamped Plan Set', null, 3500, 'DES/ENG', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('des-eng-load-calculations', 'Load Calculations', null, 900, 'DES/ENG', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('des-eng-private-utility-mark-out-and-coordination', 'Private Utility Mark-Out And Coordination', 'TBD - if public property, it''s free. this can range from $800-$2000', 2000, 'DES/ENG', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('des-eng-site-walk-evaluation', 'Site Walk / Evaluation', 'We can credit this back', 400, 'DES/ENG', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('design-engineering-as-built', 'As Built', 'EA', 900, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-base-design-eng-3-4-sheet-site-plan-riser-1-line-cd50-cd100', 'Base Design/Eng-3-4 sheet, site plan, riser, 1-line, CD50-CD100', 'EA', 4250, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-load-study-load-calcs', 'Load Study/Load Calcs', 'EA', 1050, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-permit-coordination-and-filing-up-to-2-visits-in-person', 'Permit Coordination and Filing-Up to 2 visits in person', 'EA', 950, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-permitting-documentation-and-submittal-includes-one-line-diagram', 'Permitting Documentation and Submittal (Includes One Line Diagram)', 'RESI', 300, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-property-line-stake-garage-field-sketch', 'Property Line Stake/Garage Field Sketch', 'EA', 1500, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-site-visit', 'Site Visit', 'EA', 1000, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('design-engineering-utility-coordination-up-to-2-visits-in-person', 'Utility Coordination-Up to 2 visits in person', 'EA', 950, 'DESIGN/ENGINEERING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('elec-lbr-installation-commissioning-of-pedestal-mounted-charger-dual-port', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', null, 1600, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-installation-commissioning-of-pedestal-mounted-charger-single-port', 'Installation & Commissioning Of Pedestal-Mounted Charger - Single Port', null, 850, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-installation-commissioning-of-wall-mounted-charger-dual-port', 'Installation & Commissioning Of Wall-Mounted Charger - Dual Port', null, 1600, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-installation-commissioning-of-wall-mounted-charger-single-port', 'Installation & Commissioning Of Wall-Mounted Charger - Single Port', null, 850, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-mat-austin-energy-approved-sub-meter', 'Austin Energy Approved Sub-Meter', null, 1300, 'ELEC LBR MAT', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-mat-emt-conduit-wire-breakers-connectors-and-strut-cradles-includes-materials-lab', 'Emt Conduit, Wire, Breakers, Connectors, And Strut Cradles (Includes Materials + Labor)', null, 32, 'ELEC LBR MAT', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-mat-ev-dedicated-sub-panel-for-sub-metering-includes-materials-labor', 'EV Dedicated Sub-Panel for Sub-Metering (Includes Materials + Labor)', null, 1050, 'ELEC LBR MAT', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-removal-and-disposal-of-existing-ev-chargers', 'Removal And Disposal Of Existing Ev Chargers', null, 400, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('elec-lbr-xeal-installation-commissioning-of-pedestal-mounted-charger-dual-port', 'Xeal - Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', null, 2300, 'ELEC LBR', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('electrical-furnish-install-1-1-4-emt-conduit', 'Furnish & Install 1 1/4 EMT Conduit', 'LF', 18, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-1-conduit-pvc-schedule-40', 'Furnish & Install 1" Conduit (PVC Schedule 40)', 'LF', 15, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--commissioning-only', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 25, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--equipment-only', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--garage-full-turnkey', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--install-commission', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--parking-lot-full-turnkey', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--remove-replace', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--resi-ev', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-2-conduit-pvc-schedule-40--supercharger', 'Furnish & Install 2" Conduit (PVC Schedule 40)', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('electrical-furnish-install-3-conduit-pvc-schedule-40', 'Furnish & Install 3" Conduit (PVC Schedule 40)', 'LF', 20, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-4-conduit-pvc-schedule-40', 'Furnish & Install 4" Conduit (PVC Schedule 40)', 'LF', 24, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-4-emt-conduit', 'Furnish & Install 4" EMT Conduit', 'LF', 85, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-emt-conduit-up-to-2-w-up-to-4-conductors', 'Furnish & Install EMT Conduit-Up to 2" w/ up to #4 Conductors', 'LF', 32, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-furnish-install-pvc-schedule-40-up-to-2-w-4-conductors', 'Furnish & Install PVC Schedule 40-Up to 2" w/ #4 Conductors', 'LF', 20, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--commissioning-only', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1800, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--equipment-only', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--garage-full-turnkey', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--install-commission', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--parking-lot-full-turnkey', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--remove-replace', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--resi-ev', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-dual-port--supercharger', 'Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 1850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('electrical-installation-commissioning-of-pedestal-mounted-charger-single-port', 'Installation & Commissioning Of Pedestal-Mounted Charger - Single Port', 'EA', 975, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-commissioning-of-wall-mounted-charger-dual-port', 'Installation & Commissioning Of Wall-Mounted Charger - Dual Port', 'EA', 1600, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-commissioning-of-wall-mounted-charger-single-port', 'Installation & Commissioning Of Wall-Mounted Charger - Single Port', 'EA', 850, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-commissioning-superchargers', 'Installation & Commissioning Superchargers', 'EA', 975, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('electrical-installation-of-conductors-up-to-4--commissioning-only', 'Installation of Conductors-Up to #4', 'LF', 14, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('electrical-installation-of-conductors-up-to-4--equipment-only', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('electrical-installation-of-conductors-up-to-4--garage-full-turnkey', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('electrical-installation-of-conductors-up-to-4--install-commission', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('electrical-installation-of-conductors-up-to-4--parking-lot-full-turnkey', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('electrical-installation-of-conductors-up-to-4--remove-replace', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('electrical-installation-of-conductors-up-to-4--resi-ev', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-installation-of-conductors-up-to-4--supercharger', 'Installation of Conductors-Up to #4', 'LF', 30, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('electrical-level-2-ev-charger-installation-customer-supplied-charger', 'Level 2 EV Charger Installation (Customer Supplied Charger)', 'RESI', 995, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--commissioning-only', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--equipment-only', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--garage-full-turnkey', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--install-commission', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--parking-lot-full-turnkey', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--remove-replace', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--resi-ev', 'Removal And Disposal Of Existing Ev Charger', 'EA', 400, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('electrical-removal-and-disposal-of-existing-ev-charger--supercharger', 'Removal And Disposal Of Existing Ev Charger', 'EA', 100, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('electrical-xeal-installation-commissioning-of-pedestal-mounted-charger-dual-port', 'Xeal - Installation & Commissioning Of Pedestal-Mounted Charger - Dual Port', 'EA', 2300, 'ELECTRICAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('equipment-base-design-eng-3-4-sheet-site-plan-riser-1-line-cd50-cd100', 'Base Design/Eng-3-4 sheet, site plan, riser, 1-line, CD50-CD100', 'EA', 2500, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('equipment-concrete-wheelstops', 'Concrete Wheelstops', 'EA', 350, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-furnish-and-install-rubber-wheelstops', 'Furnish and Install Rubber Wheelstops', 'EA', 275, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-install-lighting-lighting-foundation-lighting-furnished-by-owner', 'Install Lighting & Lighting Foundation (Lighting Furnished by Owner)', 'EA', 2200, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-install-provided-bolt-down-bollard--commissioning-only', 'Install Provided Bolt-Down Bollard', 'EA', 500, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('equipment-install-provided-bolt-down-bollard--equipment-only', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('equipment-install-provided-bolt-down-bollard--garage-full-turnkey', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('equipment-install-provided-bolt-down-bollard--install-commission', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('equipment-install-provided-bolt-down-bollard--parking-lot-full-turnkey', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('equipment-install-provided-bolt-down-bollard--remove-replace', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('equipment-install-provided-bolt-down-bollard--resi-ev', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-install-provided-bolt-down-bollard--supercharger', 'Install Provided Bolt-Down Bollard', 'EA', 550, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'supercharger')),
  ('equipment-install-signage-and-stencils', 'Install Signage and Stencils', 'EA', 400, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-install-striping-per-stall', 'Install Striping-Per stall', 'EA', 220, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-misc-mounting-hardware-bos-materials-only', 'Misc. Mounting Hardware & BOS (Materials Only)', 'EA', 165, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-misc-wall-mounting-hardware-bos', 'Misc. Wall Mounting Hardware & BOS', 'RESI', 10, 'EQUIPMENT', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('equipment-pads-cast-in-place-concrete-for-integrated-curb-post-foundations-monolithic', 'Cast in Place Concrete for Integrated Curb/Post Foundations (Monolithic)', 'CY', 475, 'EQUIPMENT PADS', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('equipment-pads-cast-in-place-for-trash-recycle-bins', 'Cast in Place for Trash/Recycle Bins', 'EA', 500, 'EQUIPMENT PADS', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('equipment-pads-cast-in-place-foundations-for-posts', 'Cast in Place Foundations for Posts', 'EA', 850, 'EQUIPMENT PADS', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('material-misc-mounting-hardware-bos-materials-only', 'Misc. Mounting Hardware & BOS (Materials Only)', null, 165, 'MATERIAL', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('network-teltonika-rut-m50', 'Teltonika RUT M50', null, 2400, 'NETWORK', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('other-construction-fence', 'Construction Fence', 'LF', 13, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('other-equipment-rental', 'Equipment Rental', 'TBD', 1500, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('other-install-owner-provided-connectivity-extender', 'Install Owner Provided Connectivity Extender', 'EA', 450, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('other-install-owner-provided-wi-fi-equipment', 'Install Owner Provided Wi-Fi Equipment', 'EA', 450, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('other-mobilization-demobilization', 'Mobilization/Demobilization', 'EA', 3000, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('other-on-site-traffic-control-safety-fence', 'On-Site Traffic Control, Safety Fence', 'EA', 1100, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('other-out-of-geographic-range-per-mile-after-60-each-way', 'Out of Geographic Range-Per Mile after 60-Each way', 'EA', 10, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('other-unforeseen-rock-and-masonry-removal', 'Unforeseen Rock and Masonry Removal', 'CY', 325, 'OTHER', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('pedestal-tesla-wall-connector-pedestal--equipment-only', 'Tesla Wall Connector Pedestal', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'equipment-only')),
  ('pedestal-tesla-wall-connector-pedestal--garage-full-turnkey', 'Tesla Wall Connector Pedestal', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'garage-full-turnkey')),
  ('pedestal-tesla-wall-connector-pedestal--install-commission', 'Tesla Wall Connector Pedestal', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('pedestal-tesla-wall-connector-pedestal--parking-lot-full-turnkey', 'Tesla Wall Connector Pedestal', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'parking-lot-full-turnkey')),
  ('pedestal-tesla-wall-connector-pedestal--remove-replace', 'Tesla Wall Connector Pedestal', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'remove-replace')),
  ('pedestal-tesla-wall-connector-pedestal--resi-ev', 'Tesla Wall Connector Pedestal', 'EA', 550, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('pedestal-tesla-wall-connector-pedestal-includes-mounting-kit', 'Tesla Wall Connector Pedestal (Includes Mounting Kit)', 'EA', 515, 'PEDESTAL', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('safety-on-site-traffic-control-safety-fence-and-trench-plates', 'On-Site Traffic Control, Safety Fence, And Trench Plates', 'Depending on site conditions, number of chargers & days of work', 1100, 'SAFETY', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('site-work-ev-signage-includes-materials-labor', 'Ev Signage (Includes Materials + Labor)', 'Per Parking Spot', 300, 'SITE WORK', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('site-work-rubber-wheel-stops-includes-materials-labor', 'Rubber Wheel Stops (Includes Materials + Labor)', 'Per Parking Spot', 650, 'SITE WORK', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('site-work-steel-safety-bollards-4-x-36-42-includes-materials-labor', 'Steel Safety Bollards (4" X 36"/42") (Includes Materials + Labor)', 'Per Bollard', 550, 'SITE WORK', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('software-chargepoint-cpcld-community-1-1-year-prepaid-chargepoint-management-software-for-', 'ChargePoint CPCLD-Community-1 – 1 Year - Prepaid ChargePoint Management Software for CPF50', null, 355, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('software-chargepoint-cpf-active-fleet-application-only-initial-station-activation-configur', 'ChargePoint CPF - Active Fleet Application Only – Initial Station Activation & Configuration Service', null, 126, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'service-ticket')),
  ('software-chgpnt-cp6000-assure-1-1-yr-assure-warranty', 'CHGPNT CP6000-ASSURE-1 (1 Yr Assure Warranty)', 'CP6021B-50A', 534.88, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-chgpnt-cpcld-commercial-1-1-yr-cloud-plan', 'CHGPNT CPCLD-COMMERCIAL-1 (1 Yr Cloud Plan)', 'CT4021 - Dual', 464.84, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-chgpnt-cpcld-community-1-1-yr-cloud-plan', 'CHGPNT CPCLD-COMMUNITY-1 (1 Yr Cloud Plan)', 'CPF50 - Dual', 357, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-chgpnt-cpf-active-fleet-station-activation', 'CHGPNT CPF-ACTIVE FLEET (Station Activation)', 'CPF50 - Dual', 128, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-chgpnt-cpsupport-active-activation', 'CHGPNT CPSUPPORT-ACTIVE (Activation)', 'CT4021 - Dual', 317.11, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-chgpnt-ct4000-assure-1-1-yr-assure-warranty', 'CHGPNT CT4000-ASSURE-1 (1 Yr Assure Warranty)', 'CT4021 - Dual', 764.12, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'commissioning-only')),
  ('software-cp6021b-80a-l5-5-1-year-cloud-plan', 'CP6021B-80A-L5.5 - 1 Year Cloud Plan', 'EA', 929.68, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('software-cp6621b-80a-l5-5-1-year-cloud-plan', 'CP6621B-80A-L5.5 - 1 Year Cloud Plan', 'EA', 929.68, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('software-cpf50-dual-port-pedestal-mounted-1-year-cloud-plan', 'CPF50 - Dual Port, Pedestal Mounted - 1 Year Cloud Plan', 'EA', 713.18, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('software-ct4013-1-year-cloud-plan', 'CT4013 - 1 Year Cloud Plan', 'EA', 439.37, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('software-ct4021-1-year-cloud-plan', 'CT4021 - 1 Year Cloud Plan', 'EA', 929.68, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('software-ct4025-1-year-cloud-plan', 'CT4025 - 1 Year Cloud Plan', 'EA', 929.68, 'SOFTWARE', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('trenching-road-plates', 'Road Plates', 'LF', 48, 'TRENCHING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('trenching-trenching-no-conduit-over-36-w-and-no-more-than-4-d', 'Trenching(No Conduit)-Over 36" W and no more than 4'' D', 'LF', 67, 'TRENCHING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('trenching-trenching-no-conduit-up-to-36-w-and-no-more-than-4-d', 'Trenching (No Conduit)-Up to 36" W and no more than 4'' D', 'LF', 45, 'TRENCHING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('trenching-utility-mark-out', 'Utility Mark-out', 'EA', 2000, 'TRENCHING', 1.0, true, jsonb_build_object('sourceTemplate', 'resi-ev')),
  ('warranty-cp6021b-80a-l5-5-1-year-assure-warranty', 'CP6021B-80A-L5.5 - 1 Year Assure Warranty', 'EA', 547.62, 'WARRANTY', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('warranty-cp6621b-80a-l5-5-1-year-assure-warranty', 'CP6621B-80A-L5.5 - 1 Year Assure Warranty', 'EA', 547.62, 'WARRANTY', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('warranty-cpf50-dual-port-pedestal-mounted-1-year-assure-warranty', 'CPF50 - Dual Port, Pedestal Mounted - 1 Year Assure Warranty', 'EA', 191.03, 'WARRANTY', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('warranty-ct4021-1-year-assure-warranty', 'CT4021 - 1 Year Assure Warranty', 'EA', 764.12, 'WARRANTY', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission')),
  ('warranty-ct4025-1-year-assure-warranty', 'CT4025 - 1 Year Assure Warranty', 'EA', 764.12, 'WARRANTY', 1.0, true, jsonb_build_object('sourceTemplate', 'install-commission'))
on conflict (product_id) do nothing;
